"""
Signal History Log
==================
SQLite database that persists every signal generated by:
  - Live Intelligence tab
  - Ticker Signals tab
  - Market Briefing tickers to watch

Survives browser refreshes and new sessions.
Note: On Streamlit Cloud, data persists until the app redeploys.
For permanent storage, the db file can be downloaded from the UI.
"""

import streamlit as st
import sqlite3
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path
import os

# DB lives next to app.py
DB_PATH = Path(__file__).parent.parent / "signal_history.db"


def _get_conn():
    conn = sqlite3.connect(str(DB_PATH), check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn


def _init_db():
    """Create table if it doesn't exist."""
    conn = _get_conn()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS signals (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp     TEXT NOT NULL,
            source        TEXT NOT NULL,
            ticker        TEXT NOT NULL,
            action        TEXT NOT NULL,
            confidence    TEXT NOT NULL,
            urgency       TEXT,
            market_impact TEXT,
            time_horizon  TEXT,
            reasoning     TEXT,
            article_title TEXT,
            article_url   TEXT,
            source_feed   TEXT
        )
    """)
    conn.commit()
    conn.close()


_init_db()


def log_signal(
    source: str,          # "live_intelligence" | "ticker_signals" | "market_briefing"
    ticker: str,
    action: str,          # BUY | SHORT | HOLD | WATCH
    confidence: str,      # HIGH | MEDIUM | LOW
    urgency: str = "",
    market_impact: str = "",
    time_horizon: str = "",
    reasoning: str = "",
    article_title: str = "",
    article_url: str = "",
    source_feed: str = "",
):
    """Log a single signal to the database."""
    try:
        conn = _get_conn()
        conn.execute("""
            INSERT INTO signals
            (timestamp, source, ticker, action, confidence, urgency,
             market_impact, time_horizon, reasoning, article_title, article_url, source_feed)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            source, ticker.upper(), action.upper(), confidence.upper(),
            urgency, market_impact, time_horizon,
            reasoning[:400] if reasoning else "",
            article_title[:200] if article_title else "",
            article_url[:500] if article_url else "",
            source_feed,
        ))
        conn.commit()
        conn.close()
    except Exception as e:
        pass  # Never crash the main app because of logging


def log_signals_from_live(article: dict, analysis: dict):
    """Log all recommendations from a Live Intelligence analysis."""
    recs = analysis.get("recommendations", [])
    for rec in recs:
        ticker = rec.get("ticker", "")
        if not ticker:
            continue
        log_signal(
            source        = "live_intelligence",
            ticker        = ticker,
            action        = rec.get("action", "WATCH"),
            confidence    = rec.get("confidence", "LOW"),
            urgency       = analysis.get("urgency", ""),
            market_impact = analysis.get("market_impact", ""),
            time_horizon  = rec.get("time_horizon", ""),
            reasoning     = rec.get("reasoning", ""),
            article_title = article.get("title", ""),
            article_url   = article.get("url", ""),
            source_feed   = article.get("source", ""),
        )


def log_signals_from_ticker(ticker_result: dict):
    """Log all signals from a Ticker Signals analysis."""
    ticker  = ticker_result.get("ticker", "")
    signals = ticker_result.get("signals", [])
    for sig in signals:
        log_signal(
            source        = "ticker_signals",
            ticker        = ticker,
            action        = sig.get("action", "WATCH"),
            confidence    = sig.get("confidence", "LOW"),
            urgency       = ticker_result.get("urgency", ""),
            market_impact = ticker_result.get("market_impact", ""),
            time_horizon  = sig.get("time_horizon", ""),
            reasoning     = sig.get("reasoning", ""),
            article_title = sig.get("source_article", ""),
            article_url   = "",
            source_feed   = "ticker_analysis",
        )


def log_signals_from_briefing(tickers_to_watch: list):
    """Log tickers to watch from Market Briefing."""
    for tw in tickers_to_watch:
        log_signal(
            source        = "market_briefing",
            ticker        = tw.get("ticker", ""),
            action        = tw.get("action", "WATCH"),
            confidence    = tw.get("confidence", "LOW"),
            urgency       = "MEDIUM",
            market_impact = "",
            time_horizon  = "",
            reasoning     = tw.get("reasoning", ""),
            article_title = tw.get("catalyst", ""),
            article_url   = "",
            source_feed   = "market_briefing",
        )


def get_signals_df(days_back: int = 30, source_filter: list = None,
                   action_filter: list = None) -> pd.DataFrame:
    """Fetch signals as a DataFrame with optional filters."""
    try:
        conn   = _get_conn()
        cutoff = (datetime.now() - timedelta(days=days_back)).strftime("%Y-%m-%d %H:%M:%S")
        df     = pd.read_sql_query(
            "SELECT * FROM signals WHERE timestamp >= ? ORDER BY timestamp DESC",
            conn, params=(cutoff,)
        )
        conn.close()
    except Exception:
        return pd.DataFrame()

    if df.empty:
        return df

    if source_filter:
        df = df[df["source"].isin(source_filter)]
    if action_filter:
        df = df[df["action"].isin(action_filter)]

    return df


def get_signal_stats(df: pd.DataFrame) -> dict:
    """Compute summary statistics for the signal history."""
    if df.empty:
        return {}

    total   = len(df)
    by_act  = df["action"].value_counts().to_dict()
    by_conf = df["confidence"].value_counts().to_dict()
    by_src  = df["source"].value_counts().to_dict()

    # Most signalled tickers
    top_tickers = df["ticker"].value_counts().head(10).to_dict()

    # High confidence signals
    high_conf = df[df["confidence"] == "HIGH"]

    return {
        "total":         total,
        "by_action":     by_act,
        "by_confidence": by_conf,
        "by_source":     by_src,
        "top_tickers":   top_tickers,
        "high_conf_pct": round(len(high_conf) / total * 100, 1) if total > 0 else 0,
        "date_range":    f"{df['timestamp'].min()[:10]} → {df['timestamp'].max()[:10]}",
    }


def run_signal_history():
    """Main UI for the Signal History tab."""

    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    CARD   = "#0d1b2a"
    BORDER = "#1e3a5f"
    MUTED  = "#6b8fad"
    CYAN   = "#7dd3fc"
    TEXT   = "#c9d8e8"
    GREEN  = "#4ade80"
    RED    = "#f87171"
    AMBER  = "#fbbf24"
    BLUE   = "#38bdf8"

    st.markdown("""
    <div class="insight-card">
        <b style="color:#7dd3fc;">Persistent signal log — every signal from every tab is saved here.</b><br>
        <span style="color:#6b8fad;font-size:0.9rem;">
        Signals are saved to a local SQLite database and survive browser refreshes.
        After a few weeks you will have a real track record to analyse.
        Download the CSV at any time to keep a permanent copy.
        </span>
    </div>
    """, unsafe_allow_html=True)

    # ── Filters ────────────────────────────────────────────────────────────
    f1, f2, f3, f4 = st.columns(4)
    with f1:
        days_back = st.selectbox("Time period", [1, 7, 14, 30, 90, 365], index=3,
                                 format_func=lambda x: f"Last {x} day{'s' if x > 1 else ''}")
    with f2:
        source_filter = st.multiselect("Source", ["live_intelligence", "ticker_signals", "market_briefing"],
                                       default=["live_intelligence", "ticker_signals", "market_briefing"])
    with f3:
        action_filter = st.multiselect("Action", ["BUY", "SHORT", "HOLD", "WATCH"],
                                       default=["BUY", "SHORT", "HOLD", "WATCH"])
    with f4:
        ticker_search = st.text_input("Search ticker", placeholder="e.g. NVDA")

    df = get_signals_df(days_back=days_back, source_filter=source_filter or None,
                        action_filter=action_filter or None)

    if ticker_search.strip():
        df = df[df["ticker"].str.upper() == ticker_search.strip().upper()]

    if df.empty:
        st.info("No signals logged yet. Run Live Intelligence, Ticker Signals, or Market Briefing to start building your history.")
        return

    stats = get_signal_stats(df)

    # ── Summary metrics ────────────────────────────────────────────────────
    st.markdown('<div class="section-header">📊 Summary</div>', unsafe_allow_html=True)
    st.caption(f"Period: {stats.get('date_range','—')}  ·  Filters applied")

    m1, m2, m3, m4, m5 = st.columns(5)
    with m1:
        st.markdown(f'<div class="metric-box"><div class="label">Total Signals</div><div class="value">{stats["total"]}</div></div>', unsafe_allow_html=True)
    with m2:
        buys = stats["by_action"].get("BUY", 0)
        st.markdown(f'<div class="metric-box"><div class="label">BUY Signals</div><div class="value" style="color:#4ade80;">{buys}</div></div>', unsafe_allow_html=True)
    with m3:
        shorts = stats["by_action"].get("SHORT", 0)
        st.markdown(f'<div class="metric-box"><div class="label">SHORT Signals</div><div class="value" style="color:#f87171;">{shorts}</div></div>', unsafe_allow_html=True)
    with m4:
        hc = stats["by_confidence"].get("HIGH", 0)
        st.markdown(f'<div class="metric-box"><div class="label">HIGH Conf.</div><div class="value" style="color:#38bdf8;">{hc}</div></div>', unsafe_allow_html=True)
    with m5:
        st.markdown(f'<div class="metric-box"><div class="label">HIGH Conf %</div><div class="value">{stats["high_conf_pct"]}%</div></div>', unsafe_allow_html=True)

    st.markdown("")

    # ── Charts ─────────────────────────────────────────────────────────────
    c1, c2 = st.columns(2)

    with c1:
        # Signal action breakdown pie
        act = stats["by_action"]
        if act:
            fig, ax = plt.subplots(figsize=(5, 3.5))
            fig.patch.set_facecolor(CARD)
            ax.set_facecolor(CARD)
            colors = {"BUY": GREEN, "SHORT": RED, "HOLD": AMBER, "WATCH": BLUE}
            pie_colors = [colors.get(k, MUTED) for k in act.keys()]
            wedges, texts, autotexts = ax.pie(
                act.values(), labels=act.keys(), autopct="%1.0f%%",
                colors=pie_colors, startangle=90,
                textprops={"color": TEXT, "fontsize": 9}
            )
            for at in autotexts:
                at.set_color(CARD)
                at.set_fontsize(8)
            ax.set_title("Signal Breakdown", color=CYAN, fontsize=10)
            fig.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

    with c2:
        # Top tickers bar chart
        top = stats["top_tickers"]
        if top:
            fig, ax = plt.subplots(figsize=(5, 3.5))
            fig.patch.set_facecolor(CARD)
            ax.set_facecolor(CARD)
            tickers_list = list(top.keys())
            counts       = list(top.values())
            bars = ax.barh(tickers_list[::-1], counts[::-1], color=BLUE, edgecolor=BORDER, linewidth=0.5)
            ax.tick_params(colors=MUTED, labelsize=8)
            ax.set_title("Most Signalled Tickers", color=CYAN, fontsize=10)
            ax.set_xlabel("Signal Count", color=MUTED, fontsize=8)
            for spine in ax.spines.values():
                spine.set_edgecolor(BORDER)
            ax.grid(axis="x", color=BORDER, linestyle="--", linewidth=0.5, alpha=0.5)
            fig.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

    # ── Signal timeline ────────────────────────────────────────────────────
    if len(df) > 1:
        st.markdown('<div class="section-header">📅 Signal Timeline</div>', unsafe_allow_html=True)
        df_time = df.copy()
        df_time["date"] = pd.to_datetime(df_time["timestamp"]).dt.date
        daily = df_time.groupby("date").size().reset_index(name="count")

        fig, ax = plt.subplots(figsize=(12, 2.5))
        fig.patch.set_facecolor(CARD)
        ax.set_facecolor(CARD)
        ax.bar(pd.to_datetime(daily["date"]), daily["count"], color=BLUE, width=0.8, edgecolor=BORDER, linewidth=0.3)
        ax.set_title("Signals per Day", color=CYAN, fontsize=10)
        ax.tick_params(colors=MUTED, labelsize=8)
        for spine in ax.spines.values():
            spine.set_edgecolor(BORDER)
        ax.grid(axis="y", color=BORDER, linestyle="--", linewidth=0.5, alpha=0.5)
        import matplotlib.dates as mdates
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))
        fig.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

    # ── Full signal table ──────────────────────────────────────────────────
    st.markdown('<div class="section-header">📋 All Signals</div>', unsafe_allow_html=True)

    display_cols = ["timestamp", "source", "ticker", "action", "confidence",
                    "urgency", "time_horizon", "reasoning", "article_title"]
    display_df = df[[c for c in display_cols if c in df.columns]].copy()

    action_colors = {"BUY": "color: #4ade80", "SHORT": "color: #f87171",
                     "HOLD": "color: #fbbf24", "WATCH": "color: #38bdf8"}
    conf_colors   = {"HIGH": "color: #38bdf8", "MEDIUM": "color: #fbbf24", "LOW": "color: #6b8fad"}

    def color_action(val): return action_colors.get(val, "")
    def color_conf(val):   return conf_colors.get(val, "")

    styler = display_df.style
    if "action"     in display_df.columns: styler = styler.map(color_action, subset=["action"])
    if "confidence" in display_df.columns: styler = styler.map(color_conf,   subset=["confidence"])

    st.dataframe(styler, use_container_width=True, hide_index=True)

    # ── Download ───────────────────────────────────────────────────────────
    csv = df.to_csv(index=False)
    st.download_button(
        "⬇️ Download full history as CSV",
        data=csv,
        file_name=f"finsight_signals_{datetime.now().strftime('%Y%m%d')}.csv",
        mime="text/csv",
        use_container_width=True,
    )

    # ── Clear button ───────────────────────────────────────────────────────
    with st.expander("⚠️ Danger Zone"):
        if st.button("🗑️ Clear ALL signal history", key="clear_history"):
            try:
                conn = _get_conn()
                conn.execute("DELETE FROM signals")
                conn.commit()
                conn.close()
                st.success("Signal history cleared.")
                st.rerun()
            except Exception as e:
                st.error(f"Error: {e}")
